// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Context;

namespace _1.DAL.Migrations
{
    [DbContext(typeof(FpolyDBContext))]
    [Migration("20250307075645_145607032025")]
    partial class _145607032025
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.DAL.DomainClass.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenAnh")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anh");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int?>("GiaNhap")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdAnh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNsx")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaVach")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAnh");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdSize");

                    b.ToTable("ChiTietGiay");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietKhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietGiay");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.DeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChatLieu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ChieuCao")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeGiay");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GiaoCa", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChuPhatSinh")
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IdChuCuaHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVienTiepTheo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVienTrongCa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianGiaoCa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianNhanCa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianReset")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienBatDauCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienKhac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienMat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienMatCaTruoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienMatRut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienPhatSinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienTrongCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNhanVienTrongCa");

                    b.ToTable("GiaoCa");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiHinhThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("Datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("Datetime");

                    b.Property<decimal?>("TongTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("HinhThucThanhToan");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("ChuyenKhoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GiamGia")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IdCa")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraHang")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenSp")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienKhachDua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienMat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienShip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCa");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdSanPham");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTichDiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietGiay");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("Datetime");

                    b.Property<string>("QuocGia")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDem")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KieuDang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KieuDang");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("Datetime");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDem")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NSX");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.Anh", "IdAnhNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdAnh");

                    b.HasOne("_1.DAL.DomainClass.ChatLieu", "IdChatLieuNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("_1.DAL.DomainClass.DeGiay", "IdDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdDeGiay");

                    b.HasOne("_1.DAL.DomainClass.KieuDang", "IdKieuDangNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdKieuDang");

                    b.HasOne("_1.DAL.DomainClass.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac");

                    b.HasOne("_1.DAL.DomainClass.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx");

                    b.HasOne("_1.DAL.DomainClass.SanPham", "IdSanPhamNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSanPham");

                    b.HasOne("_1.DAL.DomainClass.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize");

                    b.Navigation("IdAnhNavigation");

                    b.Navigation("IdChatLieuNavigation");

                    b.Navigation("IdDeGiayNavigation");

                    b.Navigation("IdKieuDangNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSanPhamNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("IdChiTietGiay");

                    b.HasOne("_1.DAL.DomainClass.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("IdKhuyenMai");

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GiaoCa", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.NhanVien", "IdNhanViennNavigation")
                        .WithMany("GiaoCas")
                        .HasForeignKey("IdNhanVienTrongCa");

                    b.Navigation("IdNhanViennNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HinhThucThanhToan", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HinhThucThanhToans")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.GiaoCa", "IdCaNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdCa");

                    b.HasOne("_1.DAL.DomainClass.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("_1.DAL.DomainClass.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien");

                    b.HasOne("_1.DAL.DomainClass.SanPham", "IdSanPhamNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdSanPham");

                    b.Navigation("IdCaNavigation");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay");

                    b.HasOne("_1.DAL.DomainClass.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu");

                    b.Navigation("IdChucVuNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Anh", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChatLieu", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.DeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GiaoCa", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.Navigation("HinhThucThanhToans");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KieuDang", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.Navigation("GiaoCas");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.SanPham", b =>
                {
                    b.Navigation("ChiTietGiays");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });
#pragma warning restore 612, 618
        }
    }
}
