// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Context;

namespace _1.DAL.Migrations
{
    [DbContext(typeof(FpolyDBContext))]
    partial class FpolyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.DAL.DomainClass.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anh");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_ChatLieu");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Anh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<Guid?>("AnhsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int?>("GiaNhap")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdAnh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idChatLieu");

                    b.Property<Guid?>("IdDeGiay")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idDeGiay");

                    b.Property<Guid?>("IdKieuDang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idKieuDang");

                    b.Property<Guid?>("IdMauSac")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMauSac");

                    b.Property<Guid?>("IdNsx")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNSX");

                    b.Property<Guid?>("IdSanPham")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idSanPham");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnhsId");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdNsx");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdSize");

                    b.ToTable("ChiTietGiay");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietKhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdHoaDonChiTiet")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idHoaDonChiTiet");

                    b.Property<Guid?>("IdKhuyenMai")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idKhuyenMai");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.DeGiay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ChieuCao")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeGiay");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("DonGiaKhiGiam")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietGiay");

                    b.HasIndex("IdGioHang");

                    b.ToTable("GioHangChiTiet");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiamGia")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idKhachHang");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNhanVien");

                    b.Property<Guid?>("IdSanOham")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idSanOham");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DonGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdChiTietGiay")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idChiTietGiay");

                    b.Property<Guid?>("IdCongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idHoaDon");

                    b.Property<Guid?>("IdKhuyenMai")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idKhuyenMai");

                    b.Property<Guid?>("IdTichDiem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTichDIem");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThanhTien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietGiay");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mota")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KieuDang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KieuDang");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.MauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GioiTInh");

                    b.Property<string>("Ho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySInh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Nsx", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NSX");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.Anh", "Anhs")
                        .WithMany()
                        .HasForeignKey("AnhsId");

                    b.HasOne("_1.DAL.DomainClass.ChatLieu", "IdChatLieuNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdChatLieu")
                        .HasConstraintName("FK_ChiTietGiay_ChatLieu");

                    b.HasOne("_1.DAL.DomainClass.DeGiay", "IdDeGiayNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdDeGiay")
                        .HasConstraintName("FK_ChiTietGiay_DeGiay");

                    b.HasOne("_1.DAL.DomainClass.KieuDang", "IdKieuDangNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdKieuDang")
                        .HasConstraintName("FK_ChiTietGiay_KieuDang");

                    b.HasOne("_1.DAL.DomainClass.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdMauSac")
                        .HasConstraintName("FK_ChiTietGiay_MauSac");

                    b.HasOne("_1.DAL.DomainClass.Nsx", "IdNsxNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdNsx")
                        .HasConstraintName("FK_ChiTietGiay_NSX");

                    b.HasOne("_1.DAL.DomainClass.SanPham", "IdSanPhamNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK_ChiTietGiay_SanPham");

                    b.HasOne("_1.DAL.DomainClass.Size", "IdSizeNavigation")
                        .WithMany("ChiTietGiays")
                        .HasForeignKey("IdSize")
                        .HasConstraintName("FK_ChiTietGiay_Size");

                    b.Navigation("Anhs");

                    b.Navigation("IdChatLieuNavigation");

                    b.Navigation("IdDeGiayNavigation");

                    b.Navigation("IdKieuDangNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdNsxNavigation");

                    b.Navigation("IdSanPhamNavigation");

                    b.Navigation("IdSizeNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("IdKhuyenMai")
                        .HasConstraintName("FK_ChiTietKhuyenMai_KhuyenMai");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GioHang", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.KhachHang", "IdKhachHangNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK_GioHangKhachHang");

                    b.Navigation("IdKhachHangNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GioHangChiTiet", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .HasConstraintName("FK_GioHangChiTiet_ChiTietGiay");

                    b.HasOne("_1.DAL.DomainClass.GioHang", "IdGioHangNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .HasConstraintName("FK_GioHangChiTiet");

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdGioHangNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.KhachHang", "IdKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.HasOne("_1.DAL.DomainClass.NhanVien", "IdNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChiTietGiay", "IdChiTietGiayNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdChiTietGiay")
                        .HasConstraintName("FK_HoaDonChiTiet_ChiTietGiay");

                    b.HasOne("_1.DAL.DomainClass.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .HasConstraintName("FK_HoaDonChiTiet_HoaDon");

                    b.HasOne("_1.DAL.DomainClass.ChiTietKhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdKhuyenMai")
                        .HasConstraintName("FK_HoaDonChiTiet_ChiTietKhuyenMai");

                    b.Navigation("IdChiTietGiayNavigation");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.HasOne("_1.DAL.DomainClass.ChucVu", "IdChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu")
                        .HasConstraintName("FK_NhanVien_ChucVu");

                    b.Navigation("IdChucVuNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChatLieu", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietGiay", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChiTietKhuyenMai", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.DeGiay", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.KieuDang", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.MauSac", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Nsx", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.SanPham", b =>
                {
                    b.Navigation("ChiTietGiays");
                });

            modelBuilder.Entity("_1.DAL.DomainClass.Size", b =>
                {
                    b.Navigation("ChiTietGiays");
                });
#pragma warning restore 612, 618
        }
    }
}
